// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZ-CKK21JwV2VKGfVwCDd3lVzHeF1AV2E',
    appId: '1:397669061746:web:0d9d843771821ed61e9eeb',
    messagingSenderId: '397669061746',
    projectId: 'quickmed-12152',
    authDomain: 'quickmed-12152.firebaseapp.com',
    storageBucket: 'quickmed-12152.firebasestorage.app',
    measurementId: 'G-NPGTQ7824F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUpsdD8UlLYq0rvOidp0jKVPeNDZZWp1E',
    appId: '1:397669061746:android:941e17f48b3a25921e9eeb',
    messagingSenderId: '397669061746',
    projectId: 'quickmed-12152',
    storageBucket: 'quickmed-12152.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaYRy1J8t-47sB5ak7zIZeW8ZYaV0CD4w',
    appId: '1:397669061746:ios:2fa17ed3c5f2790d1e9eeb',
    messagingSenderId: '397669061746',
    projectId: 'quickmed-12152',
    storageBucket: 'quickmed-12152.firebasestorage.app',
    iosBundleId: 'com.example.helloWorld',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZ-CKK21JwV2VKGfVwCDd3lVzHeF1AV2E',
    appId: '1:397669061746:web:59474951e3ee89581e9eeb',
    messagingSenderId: '397669061746',
    projectId: 'quickmed-12152',
    authDomain: 'quickmed-12152.firebaseapp.com',
    storageBucket: 'quickmed-12152.firebasestorage.app',
    measurementId: 'G-BR1X9SDJGG',
  );
}
